openapi: 3.0.3

components:

  parameters:
    group_id:
      name: group_id
      in: path
      description: Group id
      required: true
      schema:
        type: number
    page:
      name: page
      in: query
      required: true
      description: Current page
      schema:
        type: number
    size:
      name: size
      in: query
      required: true
      description: Page size
      schema:
        type: number

  responses:
    BadLicense:
      description: "Bad license. Either server or request does not contain valid license."
    BadRequest:
      description: "Bad request. Check your input data."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OperationLog"


  schemas:

    FaceSDKResult:
      type: object
      required:
        - code
      properties:
        code:
          $ref: '#/components/schemas/FaceSDKResultCode'

    ImageData:
      description: "Base64 encoded image"
      type: string
      format: byte

    OperationLog:
      type: object
      properties:
        status_code:
          type: integer
        type:
          type: string
        msg:
          type: string
    Page:
      type: object
      properties:
        page:
          type: number
          example: 1
        total_pages:
          type: number
          example: 2

    Bytes:
      type: string
      format: binary

    FaceSDKResultCode:
      type: integer
      description: "Result codes from core lib."
      enum:
        - 0
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 209
        - 210
        - 211
        - 212
        - 213
        - 214
        - 215
        - 216
        - 217
        - 218
        - 219
        - 220
        - 221
        - 222
        - 223
        - 224
        - 225
        - 226
        - 227
        - 228
        - 229
      x-enum-varnames:
        - FACER_OK
        - FACER_NO_LICENSE
        - FACER_IS_NOT_INITIALIZED
        - FACER_COMMAND_IS_NOT_SUPPORTED
        - FACER_COMMAND_PARAMS_READ_ERROR
        - FACER_SEARCHER_INDEX_FILE_NOT_EXIST
        - FACER_SEARCHER_INDEX_FILE_READ_ERROR
        - FACER_SEARCHER_INDEX_FILE_DECRYPTION_ERROR
        - FACER_SEARCHER_INDEX_LOAD_ERROR
        - FACER_SEARCHER_WRONG_DESCRIPTOR_VERSION
        - FACER_SEARCHER_INDEX_FILE_ENCRYPTION_ERROR
        - FACER_SEARCHER_INDEX_FILE_SAVE_ERROR
        - FACER_SEARCHER_IMAGE_DECODE_ERROR
        - FACER_SEARCHER_ID_EXISTS_IN_INDEX
        - FACER_SEARCHER_ID_NOT_IN_INDEX
        - FACER_SEARCHER_NO_FACES
        - FACER_SEARCHER_DESCRIPTOR_EXTRACTOR_ERROR
        - FACER_SEARCHER_METADATA_READ_ERROR
        - FACER_SEARCHER_NO_SEARCH_LICENSE
        - FACER_SEARCHER_DESCRIPTOR_DECODE_ERROR
        - FACER_SEARCHER_DESCRIPTOR_WRONG_SIZE
        - FACER_SEARCHER_ZIP_IMAGE_READ_ERROR
        - FACER_SEARCHER_ZIP_META_READ_ERROR
        - FACER_SEARCHER_SIMILAR_PHOTOS_EXIST
        - FACER_SEARCHER_PERSON_ZIP_READ_ERROR
        - FACER_LESS_THAN_TWO_IMAGES_IN_REQUEST
        - FACER_SEARCHER_WRONG_ID
        - FACER_SEARCHER_ID_EXISTS_IN_DELETED
        - FACER_VIDEO_DECODE_ERROR
        - FACER_NOT_ENOUGH_FRAMES
        - FACER_OUTPUT_IS_NOT_DEFINED

    Thumbnail:
      description: "Formatted base64 face detection image."
      type: string
      format: byte

    FaceRectangular:
      description: "Rectangular area of the detected face. First element - X-axis coordinate. Second element - Y-axis coordinate. (X, Y) - left top point. Third element - rectangular width. Fourth element - rectangular height."
      type: array
      items:
        type: number
      example: [x, y, width, height]