openapi: 3.0.3

components:

  responses:
    BadLicense:
      description: "Bad license. Either server or request does not contain valid license."
    BadRequest:
      description: "Bad request. Check your input data."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/OperationLog"


  schemas:
    QualityRequest:
      type: object
      description: "If set, the portrait quality check is performed."
      properties:
        align:
          $ref: "#/components/schemas/Align"
        background:
          $ref: "#/components/schemas/RGB"
          description: "The RGB value for the background color: the silhouette of a person is cut out and the background is filled with this color."
        config:
          $ref: "#/components/schemas/QualityConfig"

    Align:
      type: object
      description: "Face image alignment and cutting, includes type, pad, cropSize."
      properties:
        type:
          $ref: "#/components/schemas/FaceAlignTypeQuality"
          description: "The dimensions ratio to the height of the required pattern, see the FaceAlignTypeQuality enum."
          example: 1
        pad:
          $ref: "#/components/schemas/RGB"
          description: "The RGB value for the color that will complement the image if this is needed for alignment."
        cropSize:
          type: array
          items:
            type: integer
          minItems: 2
          maxItems: 2
          description: "The resize value in case type matches this value. It it doesn't match, no resize is done."
          example: [420, 525]

    QualityConfig:
      type: object
      description: "The configuration that defines the list of returned quality check characteristics.
       For every characteristic, includes name, range, unit."
      properties:
        name:
          $ref: "#/components/schemas/FaceQualityConfigName"
          description: "The name of the characteristic."
          example: "Roll"
        range:
          type: array
          items:
            type: float
          minItems: 2
          maxItems: 2
          description: "The range of applicable values for this characteristic.
          If the returned in the Response value fits this range,
          the value is identified as compliant with the requirements."
          example: [x, y]
        unit:
          $ref: "#/components/schemas/FaceQualityUnit"
          description: "The units of measurement for the value."
          example: "degrees"

    QualityDetailsGroups:
      type: object
      properties:
        groupId:
          description: ""
          example: 1
          $ref: "#/components/schemas/FaceQualityDetailsGroups"
        name:
          # todo is enum too?
          type: string
          description: ""
          example: "ImageCharacteristics"
        total:
          type: integer
          description: ""
          example: 5
        compliant:
          type: integer
          description: ""
          example: 4

    QualityDetail:
      type: object
      properties:
        groupId:
          description: ""
          $ref: "#/components/schemas/FaceQualityDetailsGroups"
          example: 0
        name:
          $ref: "#/components/schemas/FaceQualityConfigName"
          description: "The name of the characteristic."
          example: "Roll"
        range:
          type: array
          description: "The range of set values for this characteristic."
          items:
            type: float
          minItems: 2
          maxItems: 2
          example: [x, y]
        status:
          $ref: "#/components/schemas/FaceQualityStatus"
          example: 1
          description: "The assessment status, see FaceQualityStatus enum"
        unit:
          $ref: "#/components/schemas/FaceQualityUnit"
          description: "The units of measurement for the value."
          example: "degrees"
        value:
          type: float
          description: "The assessed value for the characteristic, returned in the set units."
          example: 2.602179527282715

    RGB:
      type: array
      items:
        type: integer
      minItems: 3
      maxItems: 3
      example: [128, 128, 128]

    FaceQualityStatus:
      type: integer
      enum:
        - 0
        - 1
        - 2
      x-enum-varnames:
        - QUALITY_STATUS_FALSE
        - QUALITY_STATUS_TRUE
        - QUALITY_STATUS_UNDETERMINED

    FaceQualityUnit:
      type: string
      enum:
        - "pixels"
        - "relative"
        - "pcs"
        - "degrees"
        - "percent"
        - "bits"
        - "quantity"
      x-enum-varnames:
        - QUALITY_UNIT_PIXELS
        - QUALITY_UNIT_RELATIVE
        - QUALITY_UNIT_PSC
        - QUALITY_UNIT_DEGREES
        - QUALITY_UNIT_PERCENT
        - QUALITY_UNIT_BITS
        - QUALITY_UNIT_QUANTITY

    FaceQualityDetailsGroups:
      type: integer
      enum:
        - 0
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
      x-enum-varnames:
        - IMAGE_CHARACTERISTICS
        - HEAD_SIZE_AND_POSITIONS
        - FACE_QUALITY
        - EYES_CHARACTERISTICS
        - SHADOWS_AND_LIGHTNING
        - POSE_AND_EXPRESSION
        - HEAD_OCCLUSION
        - BACKGROUND

    FaceQualityConfigName:
      type: string
      enum:
        - "ImageWidth"
        - "ImageHeight"
        - "ImageWidthToHeight"
        - "ImageChannelsNumber"
        - "FaceMidPointHorizontalPosition"
        - "FaceMidPointVerticalPosition"
        - "HeadWidthRatio"
        - "HeadHeightRatio"
        - "EyesDistance"
        - "Yaw"
        - "Pitch"
        - "Roll"
        - "BlurLevel"
        - "NoiseLevel"
        - "EyeRightClosed"
        - "EyeLeftClosed"
        - "EyeRightOccluded"
        - "EyeLeftOccluded"
        - "EyesRed"
        - "EyeRightCoveredWithHair"
        - "EyeLeftCoveredWithHair"
        - "OffGaze"
        - "FaceDynamicRange"
        - "UnnaturalSkinTone"
        - "TooDark"
        - "TooLight"
        - "FaceGlare"
        - "ShadowsOnFace"
        - "DarkGlasses"
        - "ReflectionOnGlasses"
        - "FramesTooHeavy"
        - "FaceOccluded"
        - "HeadCovering"
        - "BackgroundUniformity"
        - "ShadowsOnBackground"
        - "OtherFaces"
        - "ShouldersPose"
        - "ExpressionLevel"
        - "MouthOpen"
        - "ContactLenses"
        - "ForeheadCovering"
        - "StrongMakeup"
        - "Smile"
        - "PaddingRatio"
      x-enum-varnames:
        - IMAGE_WIDTH
        - IMAGE_HEIGHT
        - IMAGE_WIDTH_TO_HEIGHT
        - IMAGE_CHANNELS_NUMBER
        - FACE_MID_POINT_HORIZONTAL_POSITION
        - FACE_MID_POINT_VERTICAL_POSITION
        - HEAD_WIDTH_RATIO
        - HEAD_HEIGHT_RATIO
        - EYES_DISTANCE
        - YAW
        - PITCH
        - ROLL
        - BLUR_LEVEL
        - NOISE_LEVEL
        - EYE_RIGHT_CLOSED
        - EYE_LEFT_CLOSED
        - EYE_RIGHT_OCCLUDED
        - EYE_LEFT_OCCLUDED
        - EYES_RED
        - EYE_RIGHT_COVERED_WITH_HAIR
        - EYE_LEFT_COVERED_WITH_HAIR
        - OFF_GAZE
        - FACE_DYNAMIC_RANGE
        - UNNATURAL_SKIN_TONE
        - TOO_DARK
        - TOO_LIGHT
        - FACE_GLARE
        - SHADOWS_ON_FACE
        - DARK_GLASSES
        - REFLECTION_ON_GLASSES
        - FRAMES_TOO_HEAVY
        - FACE_OCCLUDED
        - HEAD_COVERING
        - BACKGROUND_UNIFORMITY
        - SHADOWS_ON_BACKGROUND
        - OTHER_FACES
        - SHOULDERS_POSE
        - EXPRESSION_LEVEL
        - MOUTH_OPEN
        - CONTACT_LENSES
        - FOREHEAD_COVERING
        - STRONG_MAKEUP
        - SMILE
        - PADDING_RATIO

    FaceSDKResult:
      type: object
      required:
        - code
      properties:
        code:
          $ref: "#/components/schemas/FaceSDKResultCode"

    ImageData:
      description: "Base64 encoded image"
      type: string
      format: byte

    OperationLog:
      type: object
      properties:
        status_code:
          type: integer
        type:
          type: string
        msg:
          type: string

    Bytes:
      type: string
      format: binary

    FaceAlignTypeQuality:
      type: integer
      enum:
        - 0
        - 1
      x-enum-varnames:
        - QUALITY_ALIGN_3x4
        - ALIGN_4x5

    FaceSDKResultCode:
      type: integer
      description: "Result codes from core lib."
      enum:
        - 0
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 209
        - 210
        - 211
        - 212
        - 213
        - 214
        - 215
        - 216
        - 217
        - 218
        - 219
        - 220
        - 221
        - 222
        - 223
        - 224
        - 225
        - 226
        - 227
        - 228
        - 229
      x-enum-varnames:
        - FACER_OK
        - FACER_NO_LICENSE
        - FACER_IS_NOT_INITIALIZED
        - FACER_COMMAND_IS_NOT_SUPPORTED
        - FACER_COMMAND_PARAMS_READ_ERROR
        - FACER_SEARCHER_INDEX_FILE_NOT_EXIST
        - FACER_SEARCHER_INDEX_FILE_READ_ERROR
        - FACER_SEARCHER_INDEX_FILE_DECRYPTION_ERROR
        - FACER_SEARCHER_INDEX_LOAD_ERROR
        - FACER_SEARCHER_WRONG_DESCRIPTOR_VERSION
        - FACER_SEARCHER_INDEX_FILE_ENCRYPTION_ERROR
        - FACER_SEARCHER_INDEX_FILE_SAVE_ERROR
        - FACER_SEARCHER_IMAGE_DECODE_ERROR
        - FACER_SEARCHER_ID_EXISTS_IN_INDEX
        - FACER_SEARCHER_ID_NOT_IN_INDEX
        - FACER_SEARCHER_NO_FACES
        - FACER_SEARCHER_DESCRIPTOR_EXTRACTOR_ERROR
        - FACER_SEARCHER_METADATA_READ_ERROR
        - FACER_SEARCHER_NO_SEARCH_LICENSE
        - FACER_SEARCHER_DESCRIPTOR_DECODE_ERROR
        - FACER_SEARCHER_DESCRIPTOR_WRONG_SIZE
        - FACER_SEARCHER_ZIP_IMAGE_READ_ERROR
        - FACER_SEARCHER_ZIP_META_READ_ERROR
        - FACER_SEARCHER_SIMILAR_PHOTOS_EXIST
        - FACER_SEARCHER_PERSON_ZIP_READ_ERROR
        - FACER_LESS_THAN_TWO_IMAGES_IN_REQUEST
        - FACER_SEARCHER_WRONG_ID
        - FACER_SEARCHER_ID_EXISTS_IN_DELETED
        - FACER_VIDEO_DECODE_ERROR
        - FACER_NOT_ENOUGH_FRAMES
        - FACER_OUTPUT_IS_NOT_DEFINED

    Thumbnail:
      description: "Formatted base64 face detection image."
      type: string
      format: byte

    FaceRectangular:
      description: "Rectangular area of the detected face. First element - X-axis coordinate. Second element - Y-axis coordinate. (X, Y) - left top point. Third element - rectangular width. Fourth element - rectangular height."
      type: array
      items:
        type: number
      example: [x, y, width, height]