openapi: 3.0.3


paths:
  /detect:
    parameters:
      - $ref: './common.yml#/components/parameters/x-request'
    post:
      tags:
        - matching
      summary: "Detect face, evaluate attributes, assess the portrait quality"
      operationId: detect
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DetectRequest"
      responses:
        200:
          description: "Successful operation; the coordinates of the detected faces are returned."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetectResponse"
        403:
          $ref: "./common.yml#/components/responses/BadLicense"

components:
  schemas:
    DetectRequest:
      type: object
      properties:
        tag:
          type: string
          description: "Session identificator."
        processParam:
          $ref: "./common.yml#/components/schemas/ProcessParam"
        image:
          $ref: "./common.yml#/components/schemas/ImageData"
        thumbnails:
          description: "Whether to return the cropped portrains with the detected faces."
          type: boolean
          default: false
        attributes:
          description: "Whether to evaluate attributes, such as age and emotions."
          type: object
          properties:
            config:
              $ref: "./common.yml#/components/schemas/QualityConfigList"
    
    DetectResponse:
      allOf:
        - $ref: './common.yml#/components/schemas/FaceSDKResult'
        - type: object
          properties:
            results:
              $ref: '#/components/schemas/DetectResult'

    DetectResult:
      type: object
      required:
        - detections
      properties:
        detections:
          type: array
          items:
            $ref: "#/components/schemas/Detection"
        detectorType:
          description: "Internal."
          type: integer
        landmarksType:
          description: "Internal."
          type: integer
        scenario:
          description: "Scenario from Request processParam."
          $ref: "./common.yml#/components/schemas/FaceQualityScenarios"
        timer:
          type: float
          description: "The total time taken for the detection."
          example: 0.84793560000000001

    Detection:
      type: object
      required:
        - landmarks
        - roi
      properties:
        crop:
          description: "Base64 of the aligned and cropped portrait. Returned if align is set."
          $ref: "./common.yml#/components/schemas/ImageData"
        attributes:
          type: object
          properties:
            details:
              type: array
              items:
                type: object
                additionalProperties: true
            elapsedTime:
              type: number
              description: "The elapsed time for attribute detection."
        landmarks:
          description: "Absolute coordinates (x,y) of five points of each detected face: left eye, right eye, nose, left point of lips, right point of lips."
          type: array
          items:
            description: "Cartesian points. First element - X-axis coordinate. Second element - Y-axis coordinate."
            type: array
            items:
              type: integer
              example: [ x, y ]
          example: [ [ x, y ] ]
        quality:
          type: object
          description: "Field for checking the portrait quality. If it is not mentioned, no quality check is performed."
          properties:
            nonCompliant:
              type: array
              description: "The array of all the non-compliant assessment characteristics."
              items:
                $ref: "./common.yml#/components/schemas/FaceQualityConfigName"
              example: ["ImageWidthToHeight", "Yaw"]
            detailsGroups:
              description: "The array of the assessment results for each group of characteristics."
              type: array
              items:
                $ref: "./common.yml#/components/schemas/QualityDetailsGroups"
            details:
              type: array
              description: "The array of the assessment characteristics that were set in the request."
              items:
                $ref: "./common.yml#/components/schemas/QualityDetail"

            score:
              type: float
              description: "Returns the estimated portrait quality assessment result,
               a number from 0 to 1, where 1 is for absolute compliance."
              example: -1.0
            timer:
              type: float
              description: "The total time the quality assessment has taken."
              example: 0.42036411166191101
        roi:
          $ref: "./common.yml#/components/schemas/FaceRectangular"
        thumbnail:
          $ref: "./common.yml#/components/schemas/Thumbnail"

    FaceAttribute:
      description: "Face attributes for evaluation."
      type: string
      enum:
        - Age
        - Emotion
        - EyeLeft
        - EyeRight
        - Smile
        - Glasses
        - HeadCovering
        - ForeheadCovering
        - Mouth
        - MedicalMask
        - Occlusion
        - StrongMakeup
        - Headphones
      x-enum-varnames:
        - AGE
        - EMOTION
        - EYE_LEFT
        - EYE_RIGHT
        - SMILE
        - GLASSES
        - HEAD_COVERING
        - FOREHEAD_COVERING
        - MOUTH
        - MEDICAL_MASK
        - OCCLUSION
        - STRONG_MAKEUP
        - HEADPHONES
