openapi: 3.0.3
paths:

  /detect:
    post:
      tags:
        - matching
      summary: "Detect facial coordinates"
      operationId: detect
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DetectRequest"
      responses:
        200:
          description: "Successful operation; return detection faces with their coordinates."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetectResponse"
        403:
          $ref: "./common.yml#/components/responses/BadLicense"

components:
  schemas:
    DetectRequest:
      type: object
      properties:
        image:
          $ref: "./common.yml#/components/schemas/ImageData"
        thumbnails:
          description: "Enable formatted detections' thumbnails in the response"
          type: boolean
          default: false
        attributes:
          description: "Enable face attributions detection and face quality details"
          type: boolean
          default: false
        onlyCentralFace:
          description: "True - main face; false - all faces."
          type: boolean
          default: false

    DetectResponse:
      allOf:
        - $ref: './common.yml#/components/schemas/FaceSDKResult'
        - type: object
          properties:
            results:
              $ref: '#/components/schemas/DetectResult'

    DetectResult:
      type: object
      required:
        - detections
      properties:
        detections:
          type: array
          items:
            $ref: "#/components/schemas/Detection"
        detectorType:
          description: "Internal."
          type: integer
        landmarksType:
          description: "Internal."
          type: integer

    Detection:
      type: object
      required:
        - landmarks
        - roi
      properties:
        attributes:
          $ref: "#/components/schemas/FaceAttributes"
        faceQuality:
          $ref: "#/components/schemas/FaceQuality"
        landmarks:
          description: "Main coordinates of the detected face (eyes, nose, lips, ears and etc.)."
          type: array
          items:
            description: "Cartesian points. First element - X-axis coordinate. Second element - Y-axis coordinate."
            type: array
            items:
              type: number
              example: [ x, y ]
          example: [ [ x, y ] ]
        roi:
          $ref: "./common.yml#/components/schemas/FaceRectangular"
        rotationAngle:
          description: "Angle of rotation from the camera"
          type: number
          format: float
          example: -0.841
        thumbnail:
          $ref: "./common.yml#/components/schemas/Thumbnail"

    FaceQuality:
      description: "List of face details"
      type: object
      properties:
        details:
          type: array
          items:
            $ref: "#/components/schemas/FaceQualityDetails"
        score:
          type: number
          format: float
          example:
            score: 0.528

    FaceQualityDetails:
      description: "Face detail such as medicine mask, glasses, eyes etc."
      type: object
      properties:
        attribute:
          type: string
          description: "Attribute of face"
        score:
          type: number
          format: float
          description: "Probability of predicted value"
      example:
        attribute: "symmetry"
        score: 0.371

    FaceAttributes:
      type: object
      additionalProperties: true
      properties:
        age:
          $ref: "#/components/schemas/AttributeValue"
        artMask:
          $ref: "#/components/schemas/AttributeValue"
        electronicDevice:
          $ref: "#/components/schemas/AttributeValue"
        emotion:
          $ref: "#/components/schemas/AttributeValue"
        eyes:
          type: object
          properties:
            left:
              $ref: "#/components/schemas/AttributeValue"
            right:
              $ref: "#/components/schemas/AttributeValue"
        livenessView:
          $ref: "#/components/schemas/AttributeValue"
        occlusion:
          type: object
          properties:
            foreheadGlasses:
              $ref: "#/components/schemas/AttributeValue"
            glasses:
              $ref: "#/components/schemas/AttributeValue"
            hat:
              $ref: "#/components/schemas/AttributeValue"
            medecineMask:
              $ref: "#/components/schemas/AttributeValue"
            mouth:
              $ref: "#/components/schemas/AttributeValue"
            occlusionOther:
              $ref: "#/components/schemas/AttributeValue"
            sunglasses:
              $ref: "#/components/schemas/AttributeValue"
        quality:
          type: object
          properties:
            blur:
              type: number
              format: float
            brightness:
              type: number
              format: float
            noise:
              type: number
              format: float
        shades:
          $ref: "#/components/schemas/AttributeValue"
        symmetry:
          $ref: "#/components/schemas/AttributeValue"

    AttributeValue:
      description: "Standard value for attribute"
      type: object
      properties:
        pred:
          type: number
          description: "Prediction of neural network"
        prob:
          type: number
          description: "Probability that the current answer is correct"
        value:
          type: string
          description: "Translating prediction into the value of human language"



