openapi: 3.0.3

paths:
  /healthz:
    parameters:
      - $ref: "./common.yml#/components/parameters/x-request"
    get:
      summary: "Server healthcheck"
      description: "The `/api/healthz` endpoint performs a server health check, providing details such as the application name, license ID, serial number, validity, and product version. <br><br>Comprehensive information about service diagnostics is available on the [Monitoring page](https://docs.regulaforensics.com/develop/face-sdk/web-service/administration/monitoring/)."
      operationId: healthz
      tags:
        - healthcheck
      responses:
        200:
          description: "Device info."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceInfo"
  /readyz:
    parameters:
      - $ref: "./common.yml#/components/parameters/x-request"
    get:
      summary: "License healthcheck"
      description: "The `/api/readyz` endpoint checks the license's health to determine if the application is ready for operation. It validates the license and returns a response indicating whether the license is valid (`200`) or invalid (`400`)."
      operationId: readyz
      tags:
        - healthcheck
      responses:
        200:
          description: "The license is valid."
        400:
          description: "The license is not valid."

components:
  schemas:
    DeviceInfo:
      type: object
      required: [app, licenseId, licenseSerial, licenseValidUntil, version]
      properties:
        app:
          description: Application name.
          type: string
        licenseId:
          description: Unique license identifier.
          type: string
          nullable: true
        licenseSerial:
          description: License serial number.
          type: string
          nullable: true
        licenseValidUntil:
          description: License validity date.
          type: string
          format: date-time
          nullable: true
        version:
          description: Product version.
          type: string
          nullable: true
      example:
        app: "Regula Face Recognition Web API"
        licenseId: "4D43A2AF-E321-496C-9A4E-5A8F3D26DF0E"
        licenseSerial: "OL70786"
        licenseValidUntil: "9999-12-31T23:59:59Z"
        version: "7.5.297907.1721"
