openapi: 3.0.3

components:
  schemas:
    PersonsPage:
      allOf:
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/Person"
        - $ref: './common.yml#/components/schemas/Page'
    Person:
      allOf:
        - $ref: '#/components/schemas/PersonFields'
        - type: object
          properties:
            id:
              type: integer
            created_at:
              type: string
            updated_at:
              type: string
    PersonFields:
      type: object
      properties:
        name:
          type: string
        metadata:
          type: object
          additionalProperties: true
    ImageFields:
      type: object
      properties:
        image:
          type: object
          properties:
            content_type:
              type: string
            content:
              $ref: "./common.yml#/components/schemas/ImageData"
    Image:
      type: object
      properties:
        id:
          type: integer
        content_type:
          type: string
        created_at:
          type: string
        path:
          type: string
        url:
          type: string
    GroupPage:
      allOf:
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/Group"
        - $ref: './common.yml#/components/schemas/Page'
    Group:
      allOf:
        - $ref: '#/components/schemas/GroupToCreate'
        - type: object
          properties:
            id:
              type: integer
            created_at:
              type: string
    GroupToCreate:
      type: object
      properties:
        name:
          type: string
        metadata:
          type: object
          additionalProperties: true