openapi: 3.0.3

components:
  schemas:
    PersonsPage:
      allOf:
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/Person"
        - $ref: './common.yml#/components/schemas/Page'
    Person:
      allOf:
        - $ref: '#/components/schemas/PersonFields'
        - type: object
          properties:
            id:
              type: number
              format: integer
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
    PersonFields:
      type: object
      properties:
        name:
          type: string
        metadata:
          type: object
          additionalProperties: true
    ImageFields:
      type: object
      properties:
        content_type:
          type: string
        content:
          $ref: '#/components/schemas/ImageContent'
    ImageContent:
      type: string
      format: binary
    Image:
      type: object
      properties:
        id:
          type: number
          format: integer
        content_type:
          type: string
        created_at:
          type: string
          format: date-time
        path:
          type: string
        url:
          type: string
    GroupPage:
      allOf:
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/Group"
        - $ref: './common.yml#/components/schemas/Page'
    Group:
      allOf:
        - $ref: '#/components/schemas/GroupToCreate'
        - type: object
          properties:
            id:
              type: number
              format: integer
            created_at:
              type: string
              format: date-time
    GroupToCreate:
      type: object
      properties:
        name:
          type: string
        metadata:
          type: object
          additionalProperties: true