openapi: 3.0.3

components:
  responses:
    SearchBadParamsException:
      description: "Bad request. Check your input data."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/SearchBadParams"
  schemas:
    SearchBadParams:
      type: object
      properties:
        msg:
          type: string
          default: "Descriptor already calculated"
        status_code:
          type: int
          default: 400
        type:
          type: string
          default: "BadParamsException"
    PersonsPage:
      allOf:
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/Person"
        - $ref: './common.yml#/components/schemas/Page'
    Person:
      description: "Person response body: person ID, creation date, update date if any."
      allOf:
        - $ref: '#/components/schemas/PersonFields'
        - type: object
          properties:
            id:
              type: string
              format: uuid
              description: "Person ID."
            created_at:
              type: string
              description: "Person creation date."
            updated_at:
              type: string
              description: "Person update date."
            groups:
              type: array
              description: "List of groups this person belongs to."
              items:
                type: string
                format: uuid
    PersonFields:
      type: object
      description: "Person Request body: name and metadata."
      properties:
        tag:
          type: string
          description: "Session identificator."
        name:
          type: string
          description: "Person name."
        metadata:
          type: object
          additionalProperties: true
          description: "A free-form object containing person's extended attributes."
    ImageFields:
      type: object
      description: "Image in the request data, includes image and content_type."
      properties:
        tag:
          type: string
          description: "Session identificator."
        image:
          type: object
          description: "Uploaded image."
          properties:
            content_type:
              type: string
              description: "Original media type of the uploaded image."
            content:
              $ref: "./common.yml#/components/schemas/ImageData"
            image_url:
              type: string
              description: "Image URL, can be a link to Amazon S3, Google Storage, File System, or HTTP(S)."
            resize_options:
              $ref: "#/components/schemas/ResizeOptions"
    ResizeOptions:
      type: object
      description: "Set to resize the original image."
      properties:
        width:
          type: int
          description: "Resized image width, px."
        height:
          type: int
          description: "Resized image height, px."
        quality:
          type: int
          default: 100
          description: "Resized image quality, percent."
    Image:
      type: object
      description: "Image in the response."
      properties:
        id:
          type: integer
          description: "Response image ID."
        content_type:
          type: string
          description: "Original media type of the returned image."
        created_at:
          type: string
          description: "Returned image creation date."
        updated_at:
          type: string
          description: "Returned image update date."
        path:
          type: string
          description: "Returned image S3 path."
        url:
          type: string
          description: "Returned image URL."
        metadata:
          type: object
          additionalProperties: true
          description: "A free-form object containing person's extended attributes."
    GroupPage:
      allOf:
        - type: object
          properties:
            items:
              type: array
              description: "Array of Groups that are found during the search."
              items:
                $ref: "#/components/schemas/Group"
        - $ref: './common.yml#/components/schemas/Page'
    Group:
      allOf:
        - $ref: '#/components/schemas/GroupToCreate'
        - type: object
          description: "Additional group data in the response, includes id and created_at."
          properties:
            id:
              type: string
              format: uuid
              description: "Group ID."
            created_at:
              type: string
              description: "Group creation date."
    GroupToCreate:
      type: object
      description: "Request body of the group to create data, includes name and metadata."
      properties:
        tag:
          type: string
          description: "Session identificator."
        name:
          type: string
          description: "Group to create name."
        metadata:
          type: object
          additionalProperties: true
          description: "A free-form object containing group's extended attributes."
