openapi: 3.0.3
info:
  title: Regula FaceSDK Web API
  description: Regula FaceSDK Web API
  version: 3.2.0

servers:
  - url: http://localhost:41101/
    description: Local on-premise installation

paths:
  /api/match:
    $ref: './matching.yml#/paths/~1match'
  /api/detect:
    $ref: './detect.yml#/paths/~1detect'
