openapi: 3.0.3
info:
  version: 5.2.0
  title: Regula FaceSDK Web API
  x-logo:
    url: 'https://static-content.regulaforensics.com/Icons/Logos/Regula-logo.svg'
    href: 'https://mobile.regulaforensics.com/'
  description: |
    Regula FaceSDK Web API
    # Clients
    * [JavaScript](https://github.com/regulaforensics/FaceSDK-web-js-client) client for the browser and node.js based on axios
    * [Java](https://github.com/regulaforensics/FaceSDK-web-java-client) client compatible with jvm and android
    * [Python](https://github.com/regulaforensics/FaceSDK-web-python-client) 3.5+ client
    * [C#](https://github.com/regulaforensics/FaceSDK-web-csharp-client) client for .NET & .NET Core
  x-tagGroups:
    name: liveness
    tags:
      - liveness
      - match

servers:
  - url: http://localhost:41101/
    description: Local on-premise installation



# ~1 means '/'
paths:
  /api/match:
    $ref: './matching.yml#/paths/~1match'
  /api/match_and_search:
    $ref: './match_and_search.yml#/paths/~1match_and_search'
  /api/detect:
    $ref: './detect.yml#/paths/~1detect'
  /api/persons:
    $ref: './persons.yml#/paths/~1persons'
  /api/persons/{personId}:
    $ref: './persons.yml#/paths/~1persons~1{personId}'
  /api/persons/{personId}/images:
    $ref: './persons.yml#/paths/~1persons~1{personId}~1images'
  /api/persons/{personId}/images/{imageId}:
    $ref: './persons.yml#/paths/~1persons~1{personId}~1images~1{imageId}'
  /api/persons/{personId}/groups:
    $ref: './persons.yml#/paths/~1persons~1{personId}~1groups'
  /api/groups:
    $ref: './groups.yml#/paths/~1groups'
  /api/groups/{groupId}:
    $ref: './groups.yml#/paths/~1groups~1{groupId}'
  /api/groups/{groupId}/persons:
    $ref: './groups.yml#/paths/~1groups~1{groupId}~1persons'
  /api/search:
    $ref: './search.yml#/paths/~1search'
  /api/v2/liveness:
    $ref: './liveness.yml#/paths/~1v2~1liveness'
  /api/readiness:
    $ref: './diagnostics.yml#/paths/~1readiness'  
