openapi: 3.0.3
info:
  title: Regula FaceSDK Web API
  description: Regula FaceSDK Web API
  version: 3.2.0

servers:
  - url: http://localhost:41101/
    description: Local on-premise installation

paths:
  /api/match:
    $ref: './matching.yml#/paths/~1match'
  /api/detect:
    $ref: './detect.yml#/paths/~1detect'
  /api/persons:
    $ref: './persons.yml#/paths/~1persons'
  /api/persons/{person_id}:
    $ref: './persons.yml#/paths/~1persons~1{person_id}'
  /api/persons/{person_id}/images:
    $ref: './persons.yml#/paths/~1persons~1{person_id}~1images'
  /api/persons/{person_id}/images/{image_id}:
    $ref: './persons.yml#/paths/~1persons~1{person_id}~1images~1{image_id}'
  /api/persons/{person_id}/groups:
    $ref: './persons.yml#/paths/~1persons~1{person_id}~1groups'
  /api/groups:
    $ref: './groups.yml#/paths/~1groups'
  /api/groups/{group_id}:
    $ref: './groups.yml#/paths/~1groups~1{group_id}'
  /api/groups/{group_id}/persons:
    $ref: './groups.yml#/paths/~1groups~1{group_id}~1persons'
  /api/search:
    $ref: './search.yml#/paths/~1search'
