openapi: 3.0.3

paths:
  /v2/liveness:
    parameters:
      - $ref: './common.yml#/components/parameters/transactionId'
    get:
      tags:
        - liveness 2.0
      summary: liveness
      operationId: get_liveness_transaction_info
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionInfo"


components:
  schemas:
    TransactionInfo:
      type: object
      properties:
        code:
          type: integer
          description: "Return code value"
        sessionId:
          type: integer
          description: "Session ID"
        transactionId:
          type: string
          description: "Transaction ID"
        video:
          type: string
          description: "S3 link to transaction video"
        portrait:
          type: string
          description: "S3 link to transaction portrait"
        metadata:
          type: object
          additionalProperties: true
    LivenessTransaction:
      type: object
      properties:
        code:
          type: integer
          default: null
        sessionId:
          type: string
        status:
          type: integer
          default: null
          description: "Whether the liveness detection is confirmed (0) or not (1)"
        transactionId:
          type: string
        metadata:
          type: object
          additionalProperties: true
          description: "A free-form object containing person's extended attributes."
        elapsed:
          type: integer
          default: null
