openapi: 3.0.3

paths:
  /v2/liveness:
    parameters:
      - $ref: './common.yml#/components/parameters/transactionId'
    get:
      tags:
        - liveness 2.0
      summary: Liveness assessment
      operationId: get_liveness_transaction_info
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionInfo"

components:
  schemas:
    TransactionInfo:
      type: object
      properties:
        code:
          type: integer
          description: "Result code, one of the FaceSDKResultCode enum values. See the enum: https://docs.regulaforensics.com/develop/face-sdk/web-service/development/enums/face-sdk-result-code/"
        status:
          type: integer
          default: null
          description: "Whether the liveness detection is confirmed (0) or not (1)."
        tag:
          type: string
          description: "Session identificator."
        transactionId:
          type: string
          description: "Transaction ID, there can be several transactions within one session."
        video:
          type: string
          description: "Link to the session video."
        images:
          type: array
          description: "List of base64 images"
          items:
            type: string
            format: base64
        estimatedAge:
          type: integer
          description: "Approximate age with an accuracy of +/-3 years."
        portrait:
          type: string
          description: "Link to the portrait."
        metadata:
          type: object
          additionalProperties: true          
          description: "A free-form object containing person's extended attributes."
