openapi: 3.0.3

paths:
  /v2/liveness:
    parameters:
      - $ref: './common.yml#/components/parameters/transactionId'
    get:
      tags:
        - liveness 2.0
      summary: liveness
      operationId: get_liveness_transaction
      responses:
        200:
          description: "Returns attributes of transaction, including the liveness detection status: 0 for liveness confirmed; 1 for liveness not confirmed"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LivenessTransaction"

  /v2/liveness/metadata:
    parameters:
      - $ref: './common.yml#/components/parameters/transactionId'  # required query arg
    get:
      tags:
        - liveness 2.0   # groups of requests
      summary: metadata
      operationId: liveness_metadata # name for clients functions
      responses:
        200:
          description: "Successful operation, metadata returned: device model, screen data, frame size, app ID and version, OS version, platform, SDK version, etc."
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        400:
          description: "Bad request, no metadata available"
          content:
            application/octet-stream:
              schema:
                type: object
                additionalProperties: true
  /v2/liveness/portrait:
    parameters:
      - $ref: './common.yml#/components/parameters/transactionId'  # required query arg
    get:
      tags:
        - liveness 2.0   # groups of requests
      summary: portrait
      operationId: liveness_portrait  # name for clients functions
      responses:
        200:
          description: "Successful operation, portrait returned"
          content:
            application/octet-stream:   # response mimetype
              schema:
                type: string
                format: binary
        400:
          description: "Bad request, no portrait available"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /v2/liveness/video:
    parameters:
      - $ref: './common.yml#/components/parameters/transactionId'
    get:
      tags:
        - liveness 2.0
      summary: video
      operationId: liveness_video
      responses:
        200:
          description: "Successful operation, session video returned"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        400:
          description: "Bad request, no session video available"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

components:
  schemas:
    LivenessTransaction:
      type: object
      properties:
        code:
          type: integer
          default: null
        sessionId:
          type: string
        status:
          type: integer
          default: null
          description: "Whether the liveness detection is confirmed (0) or not (1)"
        transactionId:
          type: string
        metadata:
          type: object
          additionalProperties: true
          description: "A free-form object containing person's extended attributes."
        elapsed:
          type: integer
          default: null
