openapi: 3.0.3
paths:

  /match:
    parameters:
      - $ref: './common.yml#/components/parameters/x-request'
    post:
      tags:
        - matching
      summary: "Compare faces in all combinations"
      operationId: match
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatchRequest"
      responses:
        200:
          description: "Successful operation; the compare results are returned."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchResponse"
        403:
          $ref: "./common.yml#/components/responses/BadLicense"

components:
  schemas:

    MatchRequest:
      type: object
      required:
        - images
      properties:
        tag:
          type: string
          description: "Session identificator."
        thumbnails:
          type: boolean
          description: "Whether to return thumbnails: Base64 cropped images that contain vertically aligned faces."
          default: false
        images:
          type: array
          description: "The array of all images included in the comparison."
          items:
            $ref: "#/components/schemas/MatchImage"

    MatchImageIndex:
      type: integer
      description: "The image index number. Can be given; if not given, the index numbers are set automatically starting from 0. All index numbers must be whole and unique—not repeated."

    MatchFaceIndex:
      type: number
      description: "The detected face index number."

    MatchImage:
      type: object
      required:
        - data
      properties:
        index:
          $ref: "#/components/schemas/MatchImageIndex"
        type:
          $ref: "#/components/schemas/ImageSource"
        data:
          $ref: "./common.yml#/components/schemas/ImageData"
        detectAll:
          $ref: "#/components/schemas/detectAll"

    MatchResponse:
      allOf:
        - $ref: './common.yml#/components/schemas/FaceSDKResult'
        - type: object
          properties:
            detections:
              type: array
              description: "The array of detected faces."
              items:
                $ref: "#/components/schemas/MatchImageDetection"
            results:
              type: array
              description: "The array of matching results."
              items:
                $ref: "#/components/schemas/MatchImageResult"

    MatchImageResult:
      type: object
      required:
        - firstIndex
        - secondIndex
      properties:
        firstIndex:
          $ref: "#/components/schemas/MatchImageIndex"
        firstFaceIndex:
          $ref: "#/components/schemas/MatchFaceIndex"
        first:
          $ref: "#/components/schemas/ImageSource"
        secondIndex:
          $ref: "#/components/schemas/MatchImageIndex"
        secondFaceIndex:
          $ref: "#/components/schemas/MatchFaceIndex"
        second:
          $ref: "#/components/schemas/ImageSource"
        score:
          type: number
          description: "A dimensionless number that shows how similar the compared faces are. 0—absolutely identical faces."
        similarity:
          type: number
          description: "The detected faces similarity, %. 100%—absolutely identical faces, 0%—absolutely not identical."

    MatchImageDetection:
      type: object
      required:
        - imageIndex
        - status
      properties:
        faces:
          type: array
          description: "The array of detected faces."
          items:
            $ref: "#/components/schemas/DetectionFace"
        imageIndex:
          $ref: "#/components/schemas/MatchImageIndex"
        status:
          $ref: './common.yml#/components/schemas/FaceSDKResultCode'

    DetectionFace:
      type: object
      properties:
        faceIndex:
          $ref: "#/components/schemas/MatchFaceIndex"
        landmarks:
          description: "Absolute coordinates (x,y) of five points of each detected face: left eye, right eye, nose, left point of lips, right point of lips."
          type: array
          items:
            description: "Cartesian points. First element - X-axis coordinate. Second element - Y-axis coordinate."
            type: array
            items:
              type: number
              example: [ x, y ]
          example: [ [ x, y ] ]
        rotationAngle:
          description: "Angle of rotation of the face from the vertical axis, degrees."
          type: float
        roi:
          $ref: "./common.yml#/components/schemas/FaceRectangular"
        thumbnail:
          $ref: "./common.yml#/components/schemas/Thumbnail"

    ImageSource:
      description: "The type of the image, defines the way the comparison is performed. See the enum: https://docs.regulaforensics.com/develop/face-sdk/web-service/development/enums/image-source/"
      type: integer
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      x-enum-varnames:
        - DOCUMENT_PRINTED
        - DOCUMENT_RFID
        - LIVE
        - DOCUMENT_WITH_LIVE
        - EXTERNAL
        - GHOST

    detectAll:
      type: boolean
      description: "Whether to detect all faces in the image. If set to false, only the most central face is detected."
      default: true