openapi: 3.0.3
paths:

  /match:
    parameters:
      - $ref: './common.yml#/components/parameters/x-request'
    post:
      tags:
        - matching
      summary: "Compare provided face images in all combinations and return the similarity score for each pair."
      operationId: match
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatchRequest"
      responses:
        200:
          description: "Successful operation; the compare results are returned."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchResponse"
        403:
          $ref: "./common.yml#/components/responses/BadLicense"

components:
  schemas:

    MatchRequest:
      type: object
      required:
        - images
      properties:
        tag:
          type: string
          description: "Session identificator."
        thumbnails:
          type: boolean
          description: "Whether to return cropped portraits of the detected people."
          default: false
        images:
          type: array
          description: "Base64 images."
          items:
            $ref: "#/components/schemas/MatchImage"

    MatchImageIndex:
      type: integer
      description: "Image index used to identify input photos between themselves.
      If not specified, than input list index is used."

    MatchFaceIndex:
      type: number
      description: "Faces index used to identify faces in scope of one photo."

    MatchImage:
      type: object
      required:
        - data
      properties:
        index:
          $ref: "#/components/schemas/MatchImageIndex"
        type:
          $ref: "#/components/schemas/ImageSource"
        data:
          $ref: "./common.yml#/components/schemas/ImageData"

    MatchResponse:
      allOf:
        - $ref: './common.yml#/components/schemas/FaceSDKResult'
        - type: object
          properties:
            results:
              type: array
              description: "The array of matching results."
              items:
                $ref: "#/components/schemas/MatchImageResult"
            detections:
              type: array
              items:
                $ref: "#/components/schemas/MatchImageDetection"

    MatchImageResult:
      type: object
      required:
        - firstIndex
        - secondIndex
      properties:
        firstIndex:
          $ref: "#/components/schemas/MatchImageIndex"
        firstFaceIndex:
          $ref: "#/components/schemas/MatchFaceIndex"
        secondIndex:
          $ref: "#/components/schemas/MatchImageIndex"
        secondFaceIndex:
          $ref: "#/components/schemas/MatchFaceIndex"
        score:
          type: number
          description: "The matching score."
        similarity:
          type: number
          description: "The similarity score."
        errorCode:
          $ref: './common.yml#/components/schemas/FaceSDKResultCode'
        errorMsg:
          type: string
          description: "The error message if any."

    MatchImageDetection:
      type: object
      required:
        - imageIndex
        - status
      properties:
        faces:
          type: array
          items:
            $ref: "#/components/schemas/DetectionFace"
        imageIndex:
          $ref: "#/components/schemas/MatchImageIndex"
        status:
          $ref: './common.yml#/components/schemas/FaceSDKResultCode'

    DetectionFace:
      type: object
      properties:
        faceIndex:
          $ref: "#/components/schemas/MatchFaceIndex"
        landmarks:
          description: "Absolute coordinates (x,y) of five points of each detected face: left eye, right eye, nose, left point of lips, right point of lips."
          type: array
          items:
            description: "Cartesian points. First element - X-axis coordinate. Second element - Y-axis coordinate."
            type: array
            items:
              type: number
              example: [ x, y ]
          example: [ [ x, y ] ]
        roi:
          $ref: "./common.yml#/components/schemas/FaceRectangular"
        thumbnail:
          $ref: "./common.yml#/components/schemas/Thumbnail"

    ImageSource:
      description: "Face photo image source."
      type: integer
      enum:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      x-enum-varnames:
        - DOCUMENT_PRINTED
        - DOCUMENT_RFID
        - LIVE
        - DOCUMENT_WITH_LIVE
        - EXTERNAL
        - GHOST
