openapi: 3.0.3


paths:
  /search:
    parameters:
      - $ref: './common.yml#/components/parameters/x-request'
    post:
      tags:
        - search
      summary: Find person by image in groups
      operationId: search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/SearchRequest"
      responses:
        200:
          description: "Successful operation; the search result is returned."
          content:
            application/json:
              schema:
                $ref: "#/definitions/SearchResult"
        201:
          description: "New person created with the search photo and the data specified."
          content:
            application/json:
              schema:
                $ref: "#/definitions/SearchResult"
        400:
          $ref: "./identification.yml#/components/responses/SearchBadParamsException"

definitions:
  SearchRequest:
    allOf:
      - $ref: "#/definitions/SearchParameters"
      - $ref: "./identification.yml#/components/schemas/ImageFields"

  SearchParameters:
    type: object
    description: "Request search data."
    properties:
      createPerson:
        type: object
        description: "If a person is not found, a new person entry is created using the descriptor calculated while searching."
        properties:
          name:
            type: string
            description: "Person's name."
          metadata:
            type: object
            additionalProperties: true
            description: "A free-form object containing person's extended attributes."
      groupIds:
        type: array
        description: "IDs of the groups in which the search is performed."
        items:
          type: string
          format: uuid
  RecognizeImage:
    allOf:
      - $ref: "./identification.yml#/components/schemas/Image"
      - type: object
        properties:
          similarity:
            type: number
            format: float
            description: "Similarity score."
          distance:
            type: number
            format: float
            description: "Similarity distance score: the lower the distance, the higher the face's similarity."
  SearchResult:
    type: object
    properties:
      code:
        type: integer
        description: "Search result code."
      persons:
        type: array
        description: "Person data."
        items:
          $ref: "#/definitions/SearchPerson"
      id:
        type: string
        format: uuid
        description: "Person ID. The list of persons is sorted by decreasing ID value."
        nullable: true
      createdAt:
        type: string
        description: "Person creation date."
        nullable: true
      updatedAt:
        type: string
        description: "Person update date."
        nullable: true
      groups:
        type: array
        description: "List of groups this person belongs to."
        nullable: true
        items:
          type: string
          format: uuid
      name:
        type: string
        description: "Person name."
        nullable: true
      metadata:
        type: object
        additionalProperties: true
        description: "A free-form object containing person's extended attributes."
        nullable: true

  SearchPerson:
    allOf:
      - $ref: "./identification.yml#/components/schemas/Person"
      - type: object
        description: "Person data."
        properties:
          detection:
            $ref: "#/definitions/SearchDetection"
          images:
            type: array
            description: "Array of Person images."
            items:
              $ref: "#/definitions/RecognizeImage"

  SearchDetection:
    type: object
    description: "The array of identified persons."
    properties:
      code:
        type: integer
        description: "Internal."
      crop:
        type: string
        format: base64
        description: "Base64 of the aligned and cropped portrait."
      detectorType:
        type: integer
        description: "Internal."
      hash:
        type: string
        description: "Internal."
      idx:
        type: integer
        description: "Internal."
      image:
        type: string
        format: base64
        description: "Internal."
      landmarks:
        description: "Absolute coordinates (x,y) of five points of each detected face: left eye, right eye, nose, left point of lips, right point of lips."
        type: array
        items:
          description: "Cartesian points. First element - X-axis coordinate. Second element - Y-axis coordinate."
          type: array
          items:
            type: integer
            example: [ x, y ]
        example: [ [ x, y ] ]
      landmarksType:
        type: integer
        description: "Internal."
        example: 2
      msg:
        type: string
        description: "Internal."
      roi:
        $ref: "./common.yml#/components/schemas/FaceRectangular"
      versionSDK:
        type: string
        example: "5.2.245.687"
