openapi: 3.0.3


paths:
  /search:
    parameters:
      - $ref: './common.yml#/components/parameters/x-request'
    post:
      tags:
        - search
      summary: Find person by image in groups
      operationId: search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/SearchRequest"
      responses:
        200:
          description: "Successful operation; search result returned."
          content:
            application/json:
              schema:
                $ref: "#/definitions/SearchResult"
        201:
          description: "New person created with the search photo and the data specified."
          content:
            application/json:
              schema:
                $ref: "#/definitions/PersonCreatedResponse"
        400:
          $ref: "./identification.yml#/components/responses/SearchBadParamsException"

definitions:
  SearchRequest:
    allOf:
      - $ref: "#/definitions/SearchParameters"
      - $ref: "./identification.yml#/components/schemas/ImageFields"

  SearchParameters:
    type: object
    description: "Request search data."
    properties:
      create_person:
        type: object
        description: "If a person is not found, a new person entry is created using the descriptor calculated while searching."
        properties:
          name:
            type: string
            description: "Person's name."
          metadata:
            type: object
            additionalProperties: true
            description: "A free-form object containing person's extended attributes."
      group_ids:
        type: array
        description: "IDs of the groups in which the search is performed."
        items:
          type: integer
  PersonCreatedResponse:
    type: object
    properties:
      code:
        type: integer
        description: "Result code."
      persons:
        type: array
        description: "Array of Person images."
        items:
          $ref: "#/definitions/SearchPerson"
      metadata:
        type: object
        additionalProperties: true
        description: "A free-form object containing person's extended attributes."
  RecognizeImage:
    allOf:
      - $ref: "./identification.yml#/components/schemas/Image"
      - type: object
        properties:
          similarity:
            type: number
            format: float
            description: "Similarity score."
          distance:
            type: number
            format: float
            description: "Similarity distance score: the lower the distance, the higher the face's similarity."
  SearchResult:
    type: object
    properties:
      code:
        type: integer
        description: "Search result code."
      persons:
        type: array
        description: "Person data."
        items:
          $ref: "#/definitions/SearchPerson"

  SearchPerson:
    allOf:
      - $ref: "./identification.yml#/components/schemas/Person"
      - type: object
        description: "Person data."
        properties:
          images:
            type: array
            description: "Array of Person images."
            items:
              $ref: "#/definitions/RecognizeImage"
