openapi: 3.0.3


paths:
  /search:
    post:
      tags:
        - search
      summary: Find person by image in groups scope
      operationId: search
      requestBody:
        description: Search argument
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/SearchRequest"
      responses:
        200:
          description: Successful operation; return search result
          content:
            application/json:
              schema:
                $ref: "#/definitions/SearchResult"
        400:
          $ref: "./common.yml#/components/responses/BadRequest"

definitions:
  SearchRequest:
    allOf:
      - type: object
        properties:
          limit:
            type: integer
            default: 100
          threshold:
            type: number
            format: float
            default: 0.5f
          group_ids:
            type: array
            items:
              type: integer
      - $ref: "./identification.yml#/components/schemas/ImageFields"
  RecognizeImage:
    allOf:
      - $ref: "./identification.yml#/components/schemas/Image"
      - type: object
        properties:
          similarity:
            type: number
            format: float
  SearchResult:
    allOf:
      - $ref: "#/definitions/SearchPerson"
      - type: object
        properties:
          code:
            type: integer
  SearchPerson:
    allOf:
      - $ref: "./identification.yml#/components/schemas/Person"
      - type: object
        properties:
          images:
            type: array
            items:
              $ref: "#/definitions/RecognizeImage"