openapi: 3.0.3


paths:
  /search:
    parameters:
      - $ref: './common.yml#/components/parameters/x-request'
    post:
      tags:
        - face identification
      summary: Find person by image in groups.
      operationId: search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/definitions/SearchRequest"
      responses:
        200:
          description: "Successful operation; search result returned."
          content:
            application/json:
              schema:
                $ref: "#/definitions/SearchResult"
        400:
          $ref: "./common.yml#/components/responses/BadRequest"

definitions:
  SearchRequest:
    allOf:
      - $ref: "#/definitions/SearchParameters"
      - $ref: "./identification.yml#/components/schemas/ImageFields"

  SearchParameters:
    type: object
    description: "Request search data."
    properties:
      tag:
        type: string
      limit:
        type: integer
        default: 100
        description: "The number of returned Persons limit."
      threshold:
        type: float
        default: 1.0
        description: "The similarity distance threshold, should be between 0.0 and 2.0, where 0.0 is for returning results for only the most similar persons and 2.0 is for all the persons, even the dissimilar ones. If not set, the default 1.0 value is used."
      group_ids:
        type: array
        description: "The IDs of the groups in which the search is performed."
        items:
          type: integer

  RecognizeImage:
    allOf:
      - $ref: "./identification.yml#/components/schemas/Image"
      - type: object
        properties:
          similarity:
            type: number
            format: float
            description: "The similarity score."
          distance:
            type: number
            format: float
            description: "The similarity distance score: the lower the distance, the higher the face's similarity."
  SearchResult:
    type: object
    properties:
      code:
        type: integer
        description: "The search result code."
      persons:
        type: array
        items:
          $ref: "#/definitions/SearchPerson"

  SearchPerson:
    allOf:
      - $ref: "./identification.yml#/components/schemas/Person"
      - type: object
        description: "The array of Person images."
        properties:
          images:
            type: array
            items:
              $ref: "#/definitions/RecognizeImage"
