name: validate specification

on:
  pull_request:
    branches:
      - master

jobs:
  validate-specification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install -g redoc-cli
          npx @redocly/cli build-docs index.yml
      - run: |
          npm install -g @openapitools/openapi-generator-cli
          openapi-generator-cli validate -i index.yml
